### ISSUE TITLE
Cannot invoke python tests

### ISSUE THREAD

**Issue by Ohjeah** [darioizzo/dcgp#74]
Hi, 

I installed dcgpy as described and end up getting a `ModuleNotFoundError`

```bash
conda create -n dcgpy-dev python=3.8
conda activate  dcgpy-dev 
conda install dcgp-python -c conda-forge
python -c "from dcgpy import test; test.run_test_suite(); import pygmo; pygmo.mp_island.shutdown_pool(); pygmo.mp_bfe.shutdown_pool()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mq/repo/github/dcgp/dcgpy/__init__.py", line 2, in <module>
    from ._version import __version__
ModuleNotFoundError: No module named 'dcgpy._version'
```

**Comment by Ohjeah** [comment]
Works for me now and cannot reproduce the issue.
